# -*- mode: python; -*-

#
# Copyright (c) 2014 Juniper Networks, Inc. All rights reserved.
#

Import('CfgmEnv')
env = CfgmEnv.Clone()

utils_scripts = [
  'add_route_target.py',
  'cass-db-restore.sh',
  'chmod.py',
  'cmd_wrapper.py',
  'config_db_obj_name_validate.py',
  'config_db_obj_name_validate.sh',
  'contrail',
  'contrail-config.py',
  'contrail-status.py',
  'contrail_utils.py',
  'contrail-version',
  'contrail-version-deb',
  'contrail_veth_port.py',
  'create_floating_pool.py',
  'del_projects.py',
  'del_route_target.py',
  'demo_cfg.py',
  'demo_cmds.sh',
  'discovery_cli.py',
  'encap.py',
  'multi_tenancy.py',
  'net_policy_join.py',
  'provision_analytics_node.py',
  'provision_bgp.py',
  'provision_config_node.py',
  'provision_control.py',
  'provision_database_node.py',
  'provision_encap.py',
  'provision_forwarding_mode.py',
  'provision_linklocal.py',
  'provision_mx.py',
  'provision_physical_device.py',
  'provision_physical_router.py',
  'provision.py',
  'provision_static_route.py',
  'provision_vgw_interface.py',
  'provision_vrouter.py',
  'service_appliance.py',
  'service_appliance_set.py',
  'service_instance.py',
  'service-instance.py',
  'service_policy.py',
  'service-policy.py',
  'service_template.py',
  'service-template.py',
  'use_floating_pool.py',
  'vncop.py',
]

for utils in utils_scripts:
  env.Alias('install',env.Install(env['INSTALL_EXAMPLE'], utils))
